#!/bin/sh
# This time blocklet will use Xresources date format if defined
# or try to determine most appropriate format based on locale and GNOME settings.

#DATE_FORMAT=$(xrdb -query | grep "i3xrocks.date.format2" | cut -f 2)
DATE_FORMAT=$(xrescat i3xrocks.date.format)
BUTTON=${button:-}

if [ -z "$DATE_FORMAT" ]; then # No custom format defined, use system defaults
    COUNTRY=$(locale | grep LC_TIME | head -n1 | cut -d "=" -f 2 | cut -d "_" -f 2 | cut -d "." -f 1)
    if [ -z "$COUNTRY" ]; then
        DATE_SPEC="%m/%d"
    else
        case $COUNTRY in
            "US" | "CN" | "JP" | "KP" | "KR" | "CA" | "TW" | "HU" | "MN" | "LT" | "BT" )
                DATE_SPEC="%m/%d"
            ;;
            *)
                DATE_SPEC="%d/%m"
            ;;
        esac
    fi

    TIME_FORMAT=$(gsettings get org.gnome.desktop.interface clock-format)

    if [ "$TIME_FORMAT" == "'12h'" ]; then
        TIME_SPEC="%I:%M"
    else
        TIME_SPEC="%H:%M"
    fi

    DATE_VALUE=$(date "+ $DATE_SPEC $TIME_SPEC")
else
    DATE_VALUE=$(date "+ $DATE_FORMAT")
fi


LABEL_ICON=${icon:-$(xrdb_get i3xrocks.label.time)}
LABEL_COLOR=${label_color:-$(xrdb_get i3xrocks.label.color)}
VALUE_COLOR=${color:-$(xrdb_get i3xrocks.label.color)}
VALUE_FONT=${font:-$(xrdb_get i3xrocks.value.font)}
echo "<span color=\"$LABEL_COLOR\">$LABEL_ICON</span><span font_desc=\"$VALUE_FONT\" color=\"$VALUE_COLOR\">$DATE_VALUE </span>"

if [ "x${BUTTON}" == "x1" ]; then

 i3-msg -q "workspace number 4"
 #gnome-calendar

# WIDTH=${WIDTH:-400}
# HEIGHT=${HEIGHT:-400}
# #posX=$(($BLOCK_X - $WIDTH/4))
# #posY=$(($BLOCK_Y + 15))
# posX=2600
# posY=26

# i3-msg -q "exec yad --calendar \
#            --width=$WIDTH --height=$HEIGHT \
#	    --undecorated --fixed \
#	    --close-on-unfocus --no-buttons \
#	    --posx=$posX --posy=$posY \
#	    > /dev/null"
fi
