[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.primary]
background = "#000000"
foreground = "#cc0000"

[font]
size = 12.0

[font.normal]
family = "Meslo LGS NF"

[window]
opacity = 0.7
