#!/bin/bash

ICO_ERR=
ICO_NONE=
ICO_SOME=
COUNT=$(rofication-statusi3blocks.py)
MSG="WIP"

if [[ "$COUNT" == 0 ]]
 then
 MSG=$(echo $ICO_NONE $COUNT)
 COL=#FF0000
elif [[ "$COUNT" != 0 ]]
 then
 MSG=$(echo $ICO_SOME $COUNT)
 COL=#00FF00
else
 MSG=$(echo $ICO_ERR "ERROR")
 COL=#95E6CB
fi

echo "<span color=\"$COL\">$MSG</span>"
#echo "{\"icon\":\"$ICO\", \"color\":\"$COL\", \"value\":\"$COUNT\"}"
