#!/bin/bash

LABEL_ICON=${icon:-$(xrdb -query | grep "i3xrocks.label.capslock" | cut -f 2)}
CMD=$(xset -q | grep Caps | awk '{ print $4 }')

if [[ "$CMD" == "on" ]];then
# echo eq"$CMD"eq
 COLOR=#FF0000
else
# echo neq"$CMD"neq
 COLOR=#00FF00 
fi

echo "<span color=\"$COLOR\">$LABEL_ICON</span>"
