#!/bin/bash
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

BUTTON=${button:-}
TYPE="${BLOCK_INSTANCE:-mem}"
COLOR=${!C_NOR}

LABEL_ICON=${ICON_MEMORY}
VALUE_FONT=${FONT}
DISP=${DISPLAY}
PERCENTAGE=${PERCENTAGE}

awk -v type=$TYPE -v display=$DISP -v percentage=$PERCENTAGE -v vc="$COLOR" -v li="$LABEL_ICON" -v lc="$COLOR" -v vf="$VALUE_FONT" '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^Cached:/ {
	mem_free+=$2
}
/^MemAvailable:/ {
	mem_available=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	# fallback for mem_available
	if (mem_available == "")
		mem_available=mem_free
	# full text
	if (type == "swap") {
		to_display = swap_free/1024/1024
		if (display == "used")
			to_display = swap_total/1024/1024 - to_display
		if (percentage == "true")
			printf("<span color=\"%s\">%s</span><span font_desc=%s color=\"%s\"> %02d%%</span>\n", lc, li, vf, vc, 100 * to_display / (swap_total/1024/1024))
		else
			printf("<span color=\"%s\">%s</span><span font_desc=%s color=\"%s\"> %.1fG</span>\n", lc, li, vf, vc, to_display)
	}
	else {
		to_display = mem_free/1024/1024
		if (display == "used")
			to_display = mem_total/1024/1024 - to_display
		if (percentage == "true")
			printf("<span color=\"%s\">%s</span><span font_desc=%s color=\"%s\"> %02d%%</span>\n", lc, li, vf, vc, 100 * to_display / (mem_total/1024/1024))
		else
			printf("<span color=\"%s\">%s</span><span font_desc=%s color=\"%s\"> %.1fG</span>\n", lc, li, vf, vc, to_display)
	}
}
' /proc/meminfo

if [ "x${BUTTON}" == "x1" ]; then
    ACTION=$("/usr/bin/gnome-system-monitor --class=floating_window --show-resources-tab")
    /usr/bin/i3-msg -q exec "$ACTION"
fi
