#!/bin/bash

#set -Eeu -o pipefail

# Depends on lm-sensors (https://packages.ubuntu.com/bionic/lm-sensors)

VALUE_FONT=${FONT}
LABEL_ICON=${ICON_THERMOMETER}
TEMP=$(sensors | awk -F '(\\+|\\.)' '/(Core|Tdie)/ {sum+= $2; count++} END { printf "%d\n", sum/count}')
if [[ ${TEMP} -gt 90 ]]
then
    COLOR=${!C_ERR}
elif [[ ${TEMP} -gt 70 ]]
then
    COLOR=${!C_WARN}
else
    COLOR=${!C_NOR}
fi

echo "<span color=\"${COLOR}\">${LABEL_ICON}</span><span font_desc=${VALUE_FONT} color=\"${COLOR}\"> ${TEMP}℃</span>"
